apiVersion: v1
kind: Service
metadata:
  name: zeppelin-svc
  namespace: dataprocessing
  labels:
    app: zeppelin
    tool: spark
spec:
  ports:
    - name: ui
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: zeppelin
    tier: dataprocessing
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zeppelin-ingress
  namespace: dataprocessing
  labels:
    tool: spark
spec:
  rules:
    - host: zeppelin.YOURIP.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: zeppelin-svc
              servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zeppelin
  namespace: dataprocessing
  labels:
    app: zeppelin
    tool: spark
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zeppelin
        tier: dataprocessing 
    spec:
      containers:
      - image: pblaas/zeppelin:0.7.3_2.2.1
        resources:
          requests:
            cpu: "2000m"
            memory: "2048Mi"
        name: zeppelin
        env:
        - name: SPARKMASTER
          value: sparkmaster
        ports:
        - containerPort: 8080
          name: zeppelin

   
