apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sparkdriver
  namespace: elkspark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sparkdriver
    spec:
      containers:
      - name: kibana
        image: pblaas/spark-driver:2.2.1_bc
        imagePullPolicy: Always
        env:
        - name: SPARK_MASTER
          value: "sparkmaster.dataprocessing.svc.cluster.local:7077"
        - name: SPARK_APP
          value: "Stream-assembly-0.1.0-SNAPSHOT.jar"
        - name: SPARK_CONF
          value: "es.nodes=elasticsearch.elkspark.svc.cluster.local:9200"
        resources:
          limits:
            cpu: 2000m
            memory: 2500Mi
          requests:
            cpu: 500m
            memory: 1500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30


