apiVersion: v1
kind: Service
metadata:
  name: sparkmaster
  namespace: dataprocessing
  labels:
    app: sparkmaster
    tool: spark
spec:
  ports:
    - name: ui
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: master
      port: 7077
      protocol: TCP
      targetPort: 7077
  selector:
    app: sparkmaster
    tier: dataprocessing
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sparkmaster-ingress
  namespace: dataprocessing
  labels:
    tool: spark
spec:
  rules:
    - host: spark.YOURIP.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: sparkmaster
              servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sparkmaster
  namespace: dataprocessing
  labels:
    app: sparkmaster
    tool: spark
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sparkmaster
        tier: dataprocessing 
    spec:
      containers:
      - image: pblaas/spark:2.2.1
        command: [ "/usr/bin/supervisord" ]
        args: [ "--configuration=/opt/conf/master.conf" ]
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
        name: sparkmaster
        env:
        - name: SPARK_MASTER_HOST
          value: "0.0.0.0"
        ports:
        - containerPort: 8080
          name: sparkmaster
